/*

 UI.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\samuel\Desktop\gamebiy_tileset\tiles\UI_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 1
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define UIWidth 20
#define UIHeight 18
#define UIBank 0

extern unsigned char UI[];

/* End of UI.H */
