#include "ui_pointer.h"
/* Tile data generated by GBTD — included directly so it compiles into
   this translation unit without requiring a separate Makefile entry
   (spaces in the directory name make separate compilation awkward).    */
#include "pointer tiles/PointerSprites.c"

/* GBTD stores 16×16 tiles in column-major sub-tile order:
 *   VRAM+0 = top-left   VRAM+1 = bot-left
 *   VRAM+2 = top-right  VRAM+3 = bot-right
 *
 * pointer_move positions sprites as:
 *   OAM+0 (x,   y  ) = TL    OAM+1 (x+8, y  ) = TR
 *   OAM+2 (x,   y+8) = BL    OAM+3 (x+8, y+8) = BR
 *
 * So the set_sprite_tile assignments below cross-wire +1↔+2 to correct
 * the column-major → row-major reordering.
 */

void pointer_init(UIPointer *p, uint8_t vram_base, uint8_t oam_base) {
    p->vram_base = vram_base;
    p->oam_base  = oam_base;

    /* Load both animation frames (8 sub-tiles) into sprite VRAM */
    set_sprite_data(vram_base, 8, PointerSprites);

    /* Clear any stale OAM flags (e.g. S_PALETTE left by a previous scene).
       Pointer always uses OBP0; no priority flip; no mirror. */
    set_sprite_prop(oam_base + 0, 0);
    set_sprite_prop(oam_base + 1, 0);
    set_sprite_prop(oam_base + 2, 0);
    set_sprite_prop(oam_base + 3, 0);

    set_sprite_tile(oam_base + 0, vram_base + 0);  /* TL (GBTD index 0) */
    set_sprite_tile(oam_base + 1, vram_base + 2);  /* TR (GBTD index 2) */
    set_sprite_tile(oam_base + 2, vram_base + 1);  /* BL (GBTD index 1) */
    set_sprite_tile(oam_base + 3, vram_base + 3);  /* BR (GBTD index 3) */

    pointer_hide(p);
}

void pointer_move(UIPointer *p, uint8_t screen_x, uint8_t screen_y) {
    /* GB OAM offsets: raw_x = screen_x + 8, raw_y = screen_y + 16 */
    uint8_t ox = screen_x + 8u;
    uint8_t oy = screen_y + 16u;
    uint8_t b  = p->oam_base;

    move_sprite(b + 0, ox,      oy);       /* top-left  */
    move_sprite(b + 1, ox + 8u, oy);       /* top-right */
    move_sprite(b + 2, ox,      oy + 8u);  /* bot-left  */
    move_sprite(b + 3, ox + 8u, oy + 8u);  /* bot-right */
}

void pointer_anim_select(UIPointer *p) {
    /* GBTD column-major tile order within each 16×16 frame:
     *   vram+0=TL  vram+1=BL  vram+2=TR  vram+3=BR   (frame 0)
     *   vram+4=TL  vram+5=BL  vram+6=TR  vram+7=BR   (frame 1)
     * OAM+0→TL, OAM+1→TR, OAM+2→BL, OAM+3→BR
     * (the +1↔+2 cross-wire from pointer_init is mirrored here).   */
    uint8_t b = p->oam_base;
    uint8_t v = p->vram_base;
    uint8_t i;

    set_sprite_tile(b + 0u, v + 4u);   /* TL — frame 1 */
    set_sprite_tile(b + 1u, v + 6u);   /* TR — frame 1 */
    set_sprite_tile(b + 2u, v + 5u);   /* BL — frame 1 */
    set_sprite_tile(b + 3u, v + 7u);   /* BR — frame 1 */
    for (i = 0u; i < 10u; i++) wait_vbl_done();

    set_sprite_tile(b + 0u, v + 0u);   /* TL — frame 0 */
    set_sprite_tile(b + 1u, v + 2u);   /* TR — frame 0 */
    set_sprite_tile(b + 2u, v + 1u);   /* BL — frame 0 */
    set_sprite_tile(b + 3u, v + 3u);   /* BR — frame 0 */
    for (i = 0u; i < 4u; i++) wait_vbl_done();
}

void pointer_hide(UIPointer *p) {
    /* OAM y = 0 → sprite is above the visible area → invisible */
    uint8_t b = p->oam_base;
    move_sprite(b + 0, 0, 0);
    move_sprite(b + 1, 0, 0);
    move_sprite(b + 2, 0, 0);
    move_sprite(b + 3, 0, 0);
}
